// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmrq5A6Jvg7oRpB1AtfjrmiUO525iH05M',
    appId: '1:694657881184:web:b580a06c54a62df7821f05',
    messagingSenderId: '694657881184',
    projectId: 'punto-central-372d3',
    authDomain: 'punto-central-372d3.firebaseapp.com',
    databaseURL: 'https://punto-central-372d3-default-rtdb.firebaseio.com',
    storageBucket: 'punto-central-372d3.appspot.com',
    measurementId: 'G-JLL53F4LD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDteLEREnYoqzGm18Fk99RGEynpjK8CSuw',
    appId: '1:694657881184:android:acff5fdd819a22f7821f05',
    messagingSenderId: '694657881184',
    projectId: 'punto-central-372d3',
    databaseURL: 'https://punto-central-372d3-default-rtdb.firebaseio.com',
    storageBucket: 'punto-central-372d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2WcLfFqb8RqbEL5SuyCRdQPOPh-FMpw',
    appId: '1:694657881184:ios:eee792b9d55195f4821f05',
    messagingSenderId: '694657881184',
    projectId: 'punto-central-372d3',
    databaseURL: 'https://punto-central-372d3-default-rtdb.firebaseio.com',
    storageBucket: 'punto-central-372d3.appspot.com',
    iosBundleId: 'com.example.puntoCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2WcLfFqb8RqbEL5SuyCRdQPOPh-FMpw',
    appId: '1:694657881184:ios:97342960ef45ff89821f05',
    messagingSenderId: '694657881184',
    projectId: 'punto-central-372d3',
    databaseURL: 'https://punto-central-372d3-default-rtdb.firebaseio.com',
    storageBucket: 'punto-central-372d3.appspot.com',
    iosBundleId: 'com.example.puntoCentral.RunnerTests',
  );
}
